context:
  version: "0.70.0"

package:
  name: difftastic
  version: ${{ version }}

source:
  url: https://github.com/Wilfred/difftastic/archive/${{ version }}.tar.gz
  sha256: 4f89fdce7f58eb0521c14c14a7f76144dab5aa01400b332dd8710b550d32dc4c

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

tests:
  - script:
      - difft --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Diff that understands syntax
  homepage: https://github.com/Wilfred/difftastic
  repository: https://github.com/Wilfred/difftastic

extra:
  recipe-maintainers:
    - danielnachun
