context:
  version: "0.70.0"

package:
  name: difftastic
  version: ${{ version }}

source:
  url: https://github.com/Wilfred/difftastic/archive/${{ version }}.tar.gz
  sha256: 4f89fdce7f58eb0521c14c14a7f76144dab5aa01400b332dd8710b550d32dc4c

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - export CFLAGS="${CFLAGS} -D_BSD_SOURCE"
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - if: unix
      then:
        - make

tests:
  - package_contents:
      bin:
        - difft
      strict: true
  - script:
      - difft --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Diff that understands syntax
  homepage: https://github.com/Wilfred/difftastic
  repository: https://github.com/Wilfred/difftastic
  documentation: https://difftastic.wilfred.me.uk

extra:
  recipe-maintainers:
    - danielnachun
